2025-10-05 18:06:57.812 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_l_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/yolox_l.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 18:06:58.196 | INFO     | __main__:main:181 - Model Summary: Params: 54.15M, Gflops: 437.83
2025-10-05 18:06:58.197 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (27966), thread 'MainThread' (130083928977856):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x764e568e05e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x764e132c4c10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 184, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test, data_path=args.data_path)
                 │   │               │    │           │               │    │               │    └ '../datasets/MOT17'
                 │   │               │    │           │               │    │               └ Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x764e132c5510>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

TypeError: Exp.get_eval_loader() got an unexpected keyword argument 'data_path'
2025-10-05 18:07:00.784 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_l_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/yolox_l.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 18:07:01.172 | INFO     | __main__:main:181 - Model Summary: Params: 54.15M, Gflops: 437.83
2025-10-05 18:07:01.173 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (28016), thread 'MainThread' (129537058476480):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x75cf029d85e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x75cebf4c4c10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 184, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test, data_path=args.data_path)
                 │   │               │    │           │               │    │               │    └ '../datasets/MOT17'
                 │   │               │    │           │               │    │               └ Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x75cebf4c5480>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

TypeError: Exp.get_eval_loader() got an unexpected keyword argument 'data_path'
2025-10-05 18:22:01.804 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_l_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/yolox_l.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 18:22:02.197 | INFO     | __main__:main:181 - Model Summary: Params: 54.15M, Gflops: 437.83
2025-10-05 18:22:02.197 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 18:22:02.566 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.37s)
2025-10-05 18:22:02.566 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 18:22:02.596 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 18:22:03.081 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 18:22:03.083 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (30768), thread 'MainThread' (129287809974720):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x7594fa1e05e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7594b6accc10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 206, in main
    ckpt = torch.load(ckpt_file, map_location=loc)
           │     │    │                       └ 'cuda:0'
           │     │    └ 'pretrained/yolox_l.pth.tar'
           │     └ <function load at 0x75955cb36440>
           └ <module 'torch' from '/home/danny/.local/lib/python3.10/site-packages/torch/__init__.py'>

  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 1484, in load
    with _open_file_like(f, "rb") as opened_file:
         │               └ 'pretrained/yolox_l.pth.tar'
         └ <function _open_file_like at 0x75955cb357e0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
           │          │               └ 'rb'
           │          └ 'pretrained/yolox_l.pth.tar'
           └ <class 'torch.serialization._open_file'>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
                          │     └ 'rb'
                          └ 'pretrained/yolox_l.pth.tar'

FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/yolox_l.pth.tar'
2025-10-05 18:22:05.590 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_l_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/yolox_l.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 18:22:05.970 | INFO     | __main__:main:181 - Model Summary: Params: 54.15M, Gflops: 437.83
2025-10-05 18:22:05.971 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 18:22:06.313 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.34s)
2025-10-05 18:22:06.314 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 18:22:06.343 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 18:22:07.001 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 18:22:07.003 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (30827), thread 'MainThread' (136883528704448):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x7c7d7e4e45e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7c7d3adc8c10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 206, in main
    ckpt = torch.load(ckpt_file, map_location=loc)
           │     │    │                       └ 'cuda:0'
           │     │    └ 'pretrained/yolox_l.pth.tar'
           │     └ <function load at 0x7c7de0d3a440>
           └ <module 'torch' from '/home/danny/.local/lib/python3.10/site-packages/torch/__init__.py'>

  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 1484, in load
    with _open_file_like(f, "rb") as opened_file:
         │               └ 'pretrained/yolox_l.pth.tar'
         └ <function _open_file_like at 0x7c7de0d397e0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
           │          │               └ 'rb'
           │          └ 'pretrained/yolox_l.pth.tar'
           └ <class 'torch.serialization._open_file'>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
                          │     └ 'rb'
                          └ 'pretrained/yolox_l.pth.tar'

FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/yolox_l.pth.tar'
2025-10-05 18:23:19.344 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_l_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_l_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 18:23:19.752 | INFO     | __main__:main:181 - Model Summary: Params: 54.15M, Gflops: 437.83
2025-10-05 18:23:19.753 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 18:23:20.119 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.37s)
2025-10-05 18:23:20.119 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 18:23:20.155 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 18:23:20.636 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 18:23:20.930 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 18:23:20.930 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 18:23:21.294 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (31007), thread 'MainThread' (134854486573504):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x7aa511fe45e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7aa4ceac0c10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 233, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x7aa4d714dab0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7aa4dc5c4640>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 137, in evaluate
    n_samples = len(self.dataloader) - 1
                    │    └ None
                    └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7aa4dc5c4640>

TypeError: object of type 'NoneType' has no len()
2025-10-05 18:23:23.960 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_l_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_l_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 18:23:24.353 | INFO     | __main__:main:181 - Model Summary: Params: 54.15M, Gflops: 437.83
2025-10-05 18:23:24.353 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 18:23:24.725 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.37s)
2025-10-05 18:23:24.725 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 18:23:24.756 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 18:23:25.254 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 18:23:25.547 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 18:23:25.548 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 18:23:25.907 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (31055), thread 'MainThread' (130944350187968):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x7716abae05e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7716683c4c10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 233, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x771678545ab0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7717dabda650>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 137, in evaluate
    n_samples = len(self.dataloader) - 1
                    │    └ None
                    └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7717dabda650>

TypeError: object of type 'NoneType' has no len()
2025-10-05 19:15:51.596 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_l_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_l_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 19:15:51.982 | INFO     | __main__:main:181 - Model Summary: Params: 54.15M, Gflops: 437.83
2025-10-05 19:15:51.983 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 19:15:52.156 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.17s)
2025-10-05 19:15:52.156 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 19:15:52.182 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 19:15:52.480 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 19:15:52.860 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 19:15:52.860 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 19:16:01.069 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run007/track_results/MOT17-02-SDP.txt
2025-10-05 19:16:13.966 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run007/track_results/MOT17-04-SDP.txt
2025-10-05 19:16:22.842 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run007/track_results/MOT17-05-SDP.txt
2025-10-05 19:16:29.174 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run007/track_results/MOT17-09-SDP.txt
2025-10-05 19:16:36.945 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run007/track_results/MOT17-10-SDP.txt
2025-10-05 19:16:47.934 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run007/track_results/MOT17-11-SDP.txt
2025-10-05 19:16:56.816 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run007/track_results/MOT17-13-SDP.txt
2025-10-05 19:16:56.834 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 19:16:57.648 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 19:16:58.125 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=0.48s)
2025-10-05 19:16:58.125 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 19:16:58.154 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 19:16:59.072 | INFO     | __main__:main:236 - 
Average forward time: 15.05 ms, Average track time: 3.90 ms, Average inference time: 18.95 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.753
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.962
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.856
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.403
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.711
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.817
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.045
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.364
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.783
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.518
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.748
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.842

2025-10-05 19:16:59.073 | INFO     | __main__:main:256 - Found 21 groundtruths and 7 test files.
2025-10-05 19:16:59.076 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 19:16:59.077 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 19:16:59.077 | INFO     | __main__:main:259 - Loading files.
2025-10-05 19:17:01.495 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-02-SDP...
2025-10-05 19:17:01.696 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-13-SDP...
2025-10-05 19:17:01.867 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-04-SDP...
2025-10-05 19:17:02.373 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-10-SDP...
2025-10-05 19:17:02.548 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-05-SDP...
2025-10-05 19:17:02.736 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-11-SDP...
2025-10-05 19:17:02.945 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-09-SDP...
2025-10-05 19:17:03.071 | INFO     | __main__:main:267 - Running metrics
2025-10-05 19:17:03.993 | INFO     | __main__:main:289 - Completed
2025-10-05 19:17:06.812 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_l_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_l_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_l_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 19:17:07.240 | INFO     | __main__:main:181 - Model Summary: Params: 54.15M, Gflops: 437.83
2025-10-05 19:17:07.240 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 19:17:07.418 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.18s)
2025-10-05 19:17:07.419 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 19:17:07.432 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 19:17:07.722 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 19:17:08.108 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 19:17:08.108 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 19:17:17.149 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run008/track_results/MOT17-02-SDP.txt
2025-10-05 19:17:31.100 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run008/track_results/MOT17-04-SDP.txt
2025-10-05 19:17:40.108 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run008/track_results/MOT17-05-SDP.txt
2025-10-05 19:17:46.608 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run008/track_results/MOT17-09-SDP.txt
2025-10-05 19:17:54.433 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run008/track_results/MOT17-10-SDP.txt
2025-10-05 19:18:05.051 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run008/track_results/MOT17-11-SDP.txt
2025-10-05 19:18:14.073 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_l_mix_det/run008/track_results/MOT17-13-SDP.txt
2025-10-05 19:18:14.093 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 19:18:14.918 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 19:18:15.394 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=0.48s)
2025-10-05 19:18:15.394 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 19:18:15.418 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 19:18:16.352 | INFO     | __main__:main:236 - 
Average forward time: 15.40 ms, Average track time: 4.09 ms, Average inference time: 19.49 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.753
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.962
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.856
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.403
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.711
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.817
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.045
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.364
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.783
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.518
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.748
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.842

2025-10-05 19:18:16.353 | INFO     | __main__:main:256 - Found 21 groundtruths and 7 test files.
2025-10-05 19:18:16.353 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 19:18:16.353 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 19:18:16.353 | INFO     | __main__:main:259 - Loading files.
2025-10-05 19:18:18.696 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-02-SDP...
2025-10-05 19:18:18.889 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-13-SDP...
2025-10-05 19:18:19.055 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-04-SDP...
2025-10-05 19:18:19.579 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-10-SDP...
2025-10-05 19:18:19.749 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-05-SDP...
2025-10-05 19:18:19.928 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-11-SDP...
2025-10-05 19:18:20.128 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-09-SDP...
2025-10-05 19:18:20.345 | INFO     | __main__:main:267 - Running metrics
2025-10-05 19:18:21.224 | INFO     | __main__:main:289 - Completed
