2025-10-05 02:11:11.514 | INFO     | __main__:main:166 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, occ=True)
2025-10-05 02:11:12.249 | INFO     | __main__:main:176 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 02:11:12.250 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 02:11:12.250 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (105827), thread 'MainThread' (125397490827712):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 350, in <module>
    launch(
    └ <function launch at 0x720b304c8940>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x720aedc95bd0>

  File "/home/danny/mot/FastTracker/tools/track.py", line 179, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x720aedc964d0>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/danny/mot/FastTracker/exps/example/mot/yolox_x_mix_det.py", line 99, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 39, in __init__
    self.coco = COCO(os.path.join(self.data_dir, "annotations", self.json_file))
    │           │    │  │    │    │    │                        │    └ 'test.json'
    │           │    │  │    │    │    │                        └ <yolox.data.datasets.mot.MOTDataset object at 0x720aedabe380>
    │           │    │  │    │    │    └ '/home/danny/mot/FastTracker/datasets/mot'
    │           │    │  │    │    └ <yolox.data.datasets.mot.MOTDataset object at 0x720aedabe380>
    │           │    │  │    └ <function join at 0x720c602767a0>
    │           │    │  └ <module 'posixpath' from '/usr/lib/python3.10/posixpath.py'>
    │           │    └ <module 'os' from '/usr/lib/python3.10/os.py'>
    │           └ <class 'pycocotools.coco.COCO'>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x720aedabe380>

  File "/home/danny/.local/lib/python3.10/site-packages/pycocotools/coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
              └ '/home/danny/mot/FastTracker/datasets/mot/annotations/test.json'

FileNotFoundError: [Errno 2] No such file or directory: '/home/danny/mot/FastTracker/datasets/mot/annotations/test.json'
2025-10-05 02:11:15.003 | INFO     | __main__:main:166 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, occ=True)
2025-10-05 02:11:15.667 | INFO     | __main__:main:176 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 02:11:15.667 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 02:11:15.668 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (105906), thread 'MainThread' (133241732850112):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 350, in <module>
    launch(
    └ <function launch at 0x792d858fff40>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x792d4f1aa3b0>

  File "/home/danny/mot/FastTracker/tools/track.py", line 179, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x792d4f1aac20>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/danny/mot/FastTracker/exps/example/mot/yolox_x_mix_det.py", line 99, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 39, in __init__
    self.coco = COCO(os.path.join(self.data_dir, "annotations", self.json_file))
    │           │    │  │    │    │    │                        │    └ 'test.json'
    │           │    │  │    │    │    │                        └ <yolox.data.datasets.mot.MOTDataset object at 0x792d4efb4460>
    │           │    │  │    │    │    └ '/home/danny/mot/FastTracker/datasets/mot'
    │           │    │  │    │    └ <yolox.data.datasets.mot.MOTDataset object at 0x792d4efb4460>
    │           │    │  │    └ <function join at 0x792ec16767a0>
    │           │    │  └ <module 'posixpath' from '/usr/lib/python3.10/posixpath.py'>
    │           │    └ <module 'os' from '/usr/lib/python3.10/os.py'>
    │           └ <class 'pycocotools.coco.COCO'>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x792d4efb4460>

  File "/home/danny/.local/lib/python3.10/site-packages/pycocotools/coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
              └ '/home/danny/mot/FastTracker/datasets/mot/annotations/test.json'

FileNotFoundError: [Errno 2] No such file or directory: '/home/danny/mot/FastTracker/datasets/mot/annotations/test.json'
2025-10-05 03:23:34.585 | INFO     | __main__:main:166 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, occ=True)
2025-10-05 03:23:35.212 | INFO     | __main__:main:176 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 03:23:35.212 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 03:23:35.212 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (110046), thread 'MainThread' (140705656963520):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 350, in <module>
    launch(
    └ <function launch at 0x7ff766d0ff40>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7ff7236b23b0>

  File "/home/danny/mot/FastTracker/tools/track.py", line 179, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x7ff7236b2c20>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/danny/mot/FastTracker/exps/example/mot/yolox_x_mix_det.py", line 99, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 39, in __init__
    self.coco = COCO(os.path.join(self.data_dir, "annotations", self.json_file))
    │           │    │  │    │    │    │                        │    └ 'test.json'
    │           │    │  │    │    │    │                        └ <yolox.data.datasets.mot.MOTDataset object at 0x7ff723883f70>
    │           │    │  │    │    │    └ '/home/danny/mot/FastTracker/datasets/mot'
    │           │    │  │    │    └ <yolox.data.datasets.mot.MOTDataset object at 0x7ff723883f70>
    │           │    │  │    └ <function join at 0x7ff895f7a7a0>
    │           │    │  └ <module 'posixpath' from '/usr/lib/python3.10/posixpath.py'>
    │           │    └ <module 'os' from '/usr/lib/python3.10/os.py'>
    │           └ <class 'pycocotools.coco.COCO'>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x7ff723883f70>

  File "/home/danny/.local/lib/python3.10/site-packages/pycocotools/coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
              └ '/home/danny/mot/FastTracker/datasets/mot/annotations/test.json'

FileNotFoundError: [Errno 2] No such file or directory: '/home/danny/mot/FastTracker/datasets/mot/annotations/test.json'
2025-10-05 03:23:37.871 | INFO     | __main__:main:166 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, occ=True)
2025-10-05 03:23:38.507 | INFO     | __main__:main:176 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 03:23:38.508 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 03:23:38.508 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (110112), thread 'MainThread' (134369476702656):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 350, in <module>
    launch(
    └ <function launch at 0x7a3425203f40>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7a33e1ea63b0>

  File "/home/danny/mot/FastTracker/tools/track.py", line 179, in main
    val_loader = exp.get_eval_loader(args.batch_size, is_distributed, args.test)
                 │   │               │    │           │               │    └ False
                 │   │               │    │           │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   │               │    │           └ False
                 │   │               │    └ 1
                 │   │               └ Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_ra...
                 │   └ <function Exp.get_eval_loader at 0x7a33e1ea6c20>
                 └ ╒══════════════════╤═════════════════════════════════════════════════════════════════════════════════════════════════════════...

  File "/home/danny/mot/FastTracker/exps/example/mot/yolox_x_mix_det.py", line 99, in get_eval_loader
    valdataset = MOTDataset(
                 └ <class 'yolox.data.datasets.mot.MOTDataset'>

  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 39, in __init__
    self.coco = COCO(os.path.join(self.data_dir, "annotations", self.json_file))
    │           │    │  │    │    │    │                        │    └ 'test.json'
    │           │    │  │    │    │    │                        └ <yolox.data.datasets.mot.MOTDataset object at 0x7a33e1cb0520>
    │           │    │  │    │    │    └ '/home/danny/mot/FastTracker/datasets/mot'
    │           │    │  │    │    └ <yolox.data.datasets.mot.MOTDataset object at 0x7a33e1cb0520>
    │           │    │  │    └ <function join at 0x7a35542767a0>
    │           │    │  └ <module 'posixpath' from '/usr/lib/python3.10/posixpath.py'>
    │           │    └ <module 'os' from '/usr/lib/python3.10/os.py'>
    │           └ <class 'pycocotools.coco.COCO'>
    └ <yolox.data.datasets.mot.MOTDataset object at 0x7a33e1cb0520>

  File "/home/danny/.local/lib/python3.10/site-packages/pycocotools/coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
              └ '/home/danny/mot/FastTracker/datasets/mot/annotations/test.json'

FileNotFoundError: [Errno 2] No such file or directory: '/home/danny/mot/FastTracker/datasets/mot/annotations/test.json'
2025-10-05 03:46:53.272 | INFO     | __main__:main:167 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 03:46:53.917 | INFO     | __main__:main:177 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 03:46:53.917 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 03:46:53.957 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.04s)
2025-10-05 03:46:53.958 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 03:46:53.959 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 03:46:54.307 | INFO     | __main__:main:200 - loading checkpoint
2025-10-05 03:46:54.309 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (112212), thread 'MainThread' (137973633950144):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 351, in <module>
    launch(
    └ <function launch at 0x7d7b4da07f40>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x7d7b0a6ae3b0>

  File "/home/danny/mot/FastTracker/tools/track.py", line 202, in main
    ckpt = torch.load(ckpt_file, map_location=loc)
           │     │    │                       └ 'cuda:0'
           │     │    └ 'pretrained/bytetrack_x_mot17.pth.tar'
           │     └ <function load at 0x7d7bbff3a560>
           └ <module 'torch' from '/home/danny/.local/lib/python3.10/site-packages/torch/__init__.py'>

  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 1484, in load
    with _open_file_like(f, "rb") as opened_file:
         │               └ 'pretrained/bytetrack_x_mot17.pth.tar'
         └ <function _open_file_like at 0x7d7bbff39900>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
           │          │               └ 'rb'
           │          └ 'pretrained/bytetrack_x_mot17.pth.tar'
           └ <class 'torch.serialization._open_file'>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
                          │     └ 'rb'
                          └ 'pretrained/bytetrack_x_mot17.pth.tar'

FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/bytetrack_x_mot17.pth.tar'
2025-10-05 03:46:57.044 | INFO     | __main__:main:167 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 03:46:57.694 | INFO     | __main__:main:177 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 03:46:57.694 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 03:46:57.733 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.04s)
2025-10-05 03:46:57.733 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 03:46:57.735 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 03:46:58.018 | INFO     | __main__:main:200 - loading checkpoint
2025-10-05 03:46:58.019 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (112292), thread 'MainThread' (128011906965952):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 351, in <module>
    launch(
    └ <function launch at 0x746bdb8fff40>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤════════════════════════════════════════════════════════════════════════════════════════════════════════...
    └ <function main at 0x746ba53ae3b0>

  File "/home/danny/mot/FastTracker/tools/track.py", line 202, in main
    ckpt = torch.load(ckpt_file, map_location=loc)
           │     │    │                       └ 'cuda:0'
           │     │    └ 'pretrained/bytetrack_x_mot17.pth.tar'
           │     └ <function load at 0x746c4af36560>
           └ <module 'torch' from '/home/danny/.local/lib/python3.10/site-packages/torch/__init__.py'>

  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 1484, in load
    with _open_file_like(f, "rb") as opened_file:
         │               └ 'pretrained/bytetrack_x_mot17.pth.tar'
         └ <function _open_file_like at 0x746c4af35900>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 759, in _open_file_like
    return _open_file(name_or_buffer, mode)
           │          │               └ 'rb'
           │          └ 'pretrained/bytetrack_x_mot17.pth.tar'
           └ <class 'torch.serialization._open_file'>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/serialization.py", line 740, in __init__
    super().__init__(open(name, mode))
                          │     └ 'rb'
                          └ 'pretrained/bytetrack_x_mot17.pth.tar'

FileNotFoundError: [Errno 2] No such file or directory: 'pretrained/bytetrack_x_mot17.pth.tar'
2025-10-05 03:50:40.687 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 03:50:41.325 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 03:50:41.325 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 03:50:41.349 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.02s)
2025-10-05 03:50:41.350 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 03:50:41.352 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 03:50:41.689 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 03:50:42.205 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 03:50:42.206 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 03:50:57.783 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-01-DPM.txt
2025-10-05 03:51:11.513 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-01-FRCNN.txt
2025-10-05 03:51:25.314 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-01-SDP.txt
2025-10-05 03:52:22.691 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-03-DPM.txt
2025-10-05 03:53:20.903 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-03-FRCNN.txt
2025-10-05 03:54:18.754 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-03-SDP.txt
2025-10-05 03:54:55.514 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-06-DPM.txt
2025-10-05 03:55:32.882 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-06-FRCNN.txt
2025-10-05 03:56:08.687 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-06-SDP.txt
2025-10-05 03:56:25.653 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-07-DPM.txt
2025-10-05 03:56:42.838 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-07-FRCNN.txt
2025-10-05 03:57:00.277 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-07-SDP.txt
2025-10-05 03:57:21.549 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-08-DPM.txt
2025-10-05 03:57:43.022 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-08-FRCNN.txt
2025-10-05 03:58:04.402 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-08-SDP.txt
2025-10-05 03:58:32.888 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-12-DPM.txt
2025-10-05 03:59:02.029 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-12-FRCNN.txt
2025-10-05 03:59:31.117 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-12-SDP.txt
2025-10-05 03:59:55.673 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-14-DPM.txt
2025-10-05 04:00:21.116 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-14-FRCNN.txt
2025-10-05 04:00:45.139 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run007/track_results/MOT17-14-SDP.txt
2025-10-05 04:00:45.189 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 04:00:52.725 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (113508), thread 'MainThread' (128494972576192):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x74dc615e05e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x74dc1dfc8c10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 233, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x74dc28f49ab0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x74dbfc1b44f0>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 237, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([  446.0262,    91.0790, 17756.0000], device='cuda:0')
                   │    │                   └ [{'image_id': 1, 'category_id': 1, 'bbox': [981.1607666015625, 458.0357360839844, 77.142822265625, 188.63839721679688], 'scor...
                   │    └ <function MOTEvaluator.evaluate_prediction at 0x74dc28f49c60>
                   └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x74dbfc1b44f0>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 429, in evaluate_prediction
    cocoDt = cocoGt.loadRes(tmp)
             │      │       └ '/tmp/tmpmlpgocj_'
             │      └ <function COCO.loadRes at 0x74dc48948b80>
             └ <pycocotools.coco.COCO object at 0x74dbfc018f40>

  File "/home/danny/.local/lib/python3.10/site-packages/pycocotools/coco.py", line 314, in loadRes
    res.dataset['info'] = copy.deepcopy(self.dataset['info'])
    │   │                 │    │        │    └ {'images': [{'file_name': 'MOT17-01-DPM/img1/000001.jpg', 'id': 1, 'frame_id': 1, 'prev_image_id': -1, 'next_image_id': 2, 'v...
    │   │                 │    │        └ <pycocotools.coco.COCO object at 0x74dbfc018f40>
    │   │                 │    └ <function deepcopy at 0x74dcfdb3a050>
    │   │                 └ <module 'copy' from '/usr/lib/python3.10/copy.py'>
    │   └ {}
    └ <pycocotools.coco.COCO object at 0x74dc1c653760>

KeyError: 'info'
2025-10-05 04:01:01.054 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:01:01.719 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:01:01.720 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:01:01.743 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.02s)
2025-10-05 04:01:01.743 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:01:01.744 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:01:02.033 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:01:02.451 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:01:02.451 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:01:18.410 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run008/track_results/MOT17-01-DPM.txt
2025-10-05 04:09:53.775 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:09:54.395 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:09:54.396 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:09:54.404 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.01s)
2025-10-05 04:09:54.404 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:09:54.404 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:09:54.655 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:09:55.097 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:09:55.097 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:10:10.722 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run009/track_results/MOT17-01-SDP.txt
2025-10-05 04:11:06.754 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run009/track_results/MOT17-03-SDP.txt
2025-10-05 04:11:43.452 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run009/track_results/MOT17-06-SDP.txt
2025-10-05 04:11:59.806 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run009/track_results/MOT17-07-SDP.txt
2025-10-05 04:12:20.867 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run009/track_results/MOT17-08-SDP.txt
2025-10-05 04:12:49.212 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run009/track_results/MOT17-12-SDP.txt
2025-10-05 04:13:14.001 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run009/track_results/MOT17-14-SDP.txt
2025-10-05 04:13:14.046 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 04:13:16.586 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (117688), thread 'MainThread' (139336569094592):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x7eb8a2cec5e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7eb85f5d0c10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 233, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x7eb86f751ab0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7eb8341782e0>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 237, in evaluate
    eval_results = self.evaluate_prediction(data_list, statistics)
                   │    │                   │          └ tensor([ 148.5158,   28.1818, 5918.0000], device='cuda:0')
                   │    │                   └ [{'image_id': 1, 'category_id': 1, 'bbox': [981.1607666015625, 458.0357360839844, 77.142822265625, 188.63839721679688], 'scor...
                   │    └ <function MOTEvaluator.evaluate_prediction at 0x7eb86f751c60>
                   └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7eb8341782e0>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 429, in evaluate_prediction
    cocoDt = cocoGt.loadRes(tmp)
             │      │       └ '/tmp/tmp0dxajyxx'
             │      └ <function COCO.loadRes at 0x7eb88a054b80>
             └ <pycocotools.coco.COCO object at 0x7eb82c20d000>

  File "/home/danny/.local/lib/python3.10/site-packages/pycocotools/coco.py", line 314, in loadRes
    res.dataset['info'] = copy.deepcopy(self.dataset['info'])
    │   │                 │    │        │    └ {'images': [{'file_name': 'MOT17-01-SDP/img1/000001.jpg', 'id': 1, 'frame_id': 1, 'prev_image_id': -1, 'next_image_id': 2, 'v...
    │   │                 │    │        └ <pycocotools.coco.COCO object at 0x7eb82c20d000>
    │   │                 │    └ <function deepcopy at 0x7eb93f33a050>
    │   │                 └ <module 'copy' from '/usr/lib/python3.10/copy.py'>
    │   └ {}
    └ <pycocotools.coco.COCO object at 0x7eb85d492c80>

KeyError: 'info'
2025-10-05 04:13:21.128 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:13:21.802 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:13:21.803 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:13:21.824 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.02s)
2025-10-05 04:13:21.824 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:13:21.825 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:13:22.107 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:13:22.587 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:13:22.587 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:15:24.058 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:15:24.732 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:15:24.732 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:15:24.741 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.01s)
2025-10-05 04:15:24.741 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:15:24.742 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:15:24.993 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:15:25.510 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:15:25.511 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:15:41.572 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run011/track_results/MOT17-01-SDP.txt
2025-10-05 04:16:39.597 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run011/track_results/MOT17-03-SDP.txt
2025-10-05 04:17:15.665 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run011/track_results/MOT17-06-SDP.txt
2025-10-05 04:17:32.586 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run011/track_results/MOT17-07-SDP.txt
2025-10-05 04:17:53.929 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run011/track_results/MOT17-08-SDP.txt
2025-10-05 04:18:23.089 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run011/track_results/MOT17-12-SDP.txt
2025-10-05 04:18:47.800 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run011/track_results/MOT17-14-SDP.txt
2025-10-05 04:18:47.850 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 04:18:50.446 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 04:18:51.549 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=1.10s)
2025-10-05 04:18:51.549 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 04:18:51.642 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 04:18:52.654 | INFO     | __main__:main:236 - 
Average forward time: 25.12 ms, Average track time: 5.21 ms, Average inference time: 30.33 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

2025-10-05 04:18:52.655 | INFO     | __main__:main:256 - Found 0 groundtruths and 7 test files.
2025-10-05 04:18:52.655 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 04:18:52.655 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 04:18:52.655 | INFO     | __main__:main:259 - Loading files.
2025-10-05 04:18:53.960 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-06-SDP, skipping.
2025-10-05 04:18:53.960 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-08-SDP, skipping.
2025-10-05 04:18:53.960 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-07-SDP, skipping.
2025-10-05 04:18:53.961 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-01-SDP, skipping.
2025-10-05 04:18:53.961 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-14-SDP, skipping.
2025-10-05 04:18:53.961 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-12-SDP, skipping.
2025-10-05 04:18:53.961 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-03-SDP, skipping.
2025-10-05 04:18:53.961 | INFO     | __main__:main:267 - Running metrics
2025-10-05 04:18:53.978 | INFO     | __main__:main:289 - Completed
2025-10-05 04:18:56.936 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:18:57.628 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:18:57.628 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:18:57.638 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.01s)
2025-10-05 04:18:57.638 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:18:57.639 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:18:57.881 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:18:58.386 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:18:58.386 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:19:14.642 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run012/track_results/MOT17-01-SDP.txt
2025-10-05 04:20:14.633 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run012/track_results/MOT17-03-SDP.txt
2025-10-05 04:20:50.699 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run012/track_results/MOT17-06-SDP.txt
2025-10-05 04:21:07.512 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run012/track_results/MOT17-07-SDP.txt
2025-10-05 04:21:28.630 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run012/track_results/MOT17-08-SDP.txt
2025-10-05 04:21:56.940 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run012/track_results/MOT17-12-SDP.txt
2025-10-05 04:22:22.206 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run012/track_results/MOT17-14-SDP.txt
2025-10-05 04:22:22.251 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 04:22:24.747 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 04:22:25.815 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=1.07s)
2025-10-05 04:22:25.815 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 04:22:25.918 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 04:22:26.942 | INFO     | __main__:main:236 - 
Average forward time: 24.93 ms, Average track time: 5.66 ms, Average inference time: 30.59 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

2025-10-05 04:22:26.943 | INFO     | __main__:main:256 - Found 0 groundtruths and 7 test files.
2025-10-05 04:22:26.943 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 04:22:26.943 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 04:22:26.943 | INFO     | __main__:main:259 - Loading files.
2025-10-05 04:22:28.231 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-06-SDP, skipping.
2025-10-05 04:22:28.231 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-08-SDP, skipping.
2025-10-05 04:22:28.231 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-07-SDP, skipping.
2025-10-05 04:22:28.231 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-01-SDP, skipping.
2025-10-05 04:22:28.231 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-14-SDP, skipping.
2025-10-05 04:22:28.232 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-12-SDP, skipping.
2025-10-05 04:22:28.232 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-03-SDP, skipping.
2025-10-05 04:22:28.232 | INFO     | __main__:main:267 - Running metrics
2025-10-05 04:22:28.240 | INFO     | __main__:main:289 - Completed
2025-10-05 04:33:55.715 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:33:56.369 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:33:56.370 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:33:56.378 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.01s)
2025-10-05 04:33:56.378 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:33:56.379 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:33:56.654 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:33:57.079 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:33:57.079 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:34:12.586 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run013/track_results/MOT17-01-SDP.txt
2025-10-05 04:35:09.083 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run013/track_results/MOT17-03-SDP.txt
2025-10-05 04:35:45.283 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run013/track_results/MOT17-06-SDP.txt
2025-10-05 04:36:01.619 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run013/track_results/MOT17-07-SDP.txt
2025-10-05 04:36:22.235 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run013/track_results/MOT17-08-SDP.txt
2025-10-05 04:36:49.429 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run013/track_results/MOT17-12-SDP.txt
2025-10-05 04:37:13.464 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run013/track_results/MOT17-14-SDP.txt
2025-10-05 04:37:13.500 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 04:37:16.216 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 04:37:17.230 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=1.01s)
2025-10-05 04:37:17.231 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 04:37:17.307 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 04:37:18.249 | INFO     | __main__:main:236 - 
Average forward time: 24.75 ms, Average track time: 4.69 ms, Average inference time: 29.45 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

2025-10-05 04:37:18.250 | INFO     | __main__:main:256 - Found 21 groundtruths and 7 test files.
2025-10-05 04:37:18.250 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 04:37:18.250 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 04:37:18.250 | INFO     | __main__:main:259 - Loading files.
2025-10-05 04:37:23.434 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-06-SDP, skipping.
2025-10-05 04:37:23.434 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-08-SDP, skipping.
2025-10-05 04:37:23.434 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-07-SDP, skipping.
2025-10-05 04:37:23.434 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-01-SDP, skipping.
2025-10-05 04:37:23.434 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-14-SDP, skipping.
2025-10-05 04:37:23.434 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-12-SDP, skipping.
2025-10-05 04:37:23.435 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-03-SDP, skipping.
2025-10-05 04:37:23.435 | INFO     | __main__:main:267 - Running metrics
2025-10-05 04:37:23.443 | INFO     | __main__:main:289 - Completed
2025-10-05 04:37:26.228 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:37:26.898 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:37:26.899 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:37:26.909 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.01s)
2025-10-05 04:37:26.909 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:37:26.910 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:37:27.156 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:37:27.635 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:37:27.635 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:37:43.224 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run014/track_results/MOT17-01-SDP.txt
2025-10-05 04:38:41.240 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run014/track_results/MOT17-03-SDP.txt
2025-10-05 04:39:17.164 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run014/track_results/MOT17-06-SDP.txt
2025-10-05 04:39:34.313 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run014/track_results/MOT17-07-SDP.txt
2025-10-05 04:39:56.111 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run014/track_results/MOT17-08-SDP.txt
2025-10-05 04:40:24.339 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run014/track_results/MOT17-12-SDP.txt
2025-10-05 04:40:48.899 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run014/track_results/MOT17-14-SDP.txt
2025-10-05 04:40:48.945 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 04:40:51.511 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 04:40:52.560 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=1.05s)
2025-10-05 04:40:52.560 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 04:40:52.631 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 04:40:53.635 | INFO     | __main__:main:236 - 
Average forward time: 24.94 ms, Average track time: 5.30 ms, Average inference time: 30.24 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

2025-10-05 04:40:53.636 | INFO     | __main__:main:256 - Found 21 groundtruths and 7 test files.
2025-10-05 04:40:53.636 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 04:40:53.636 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 04:40:53.636 | INFO     | __main__:main:259 - Loading files.
2025-10-05 04:40:59.107 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-06-SDP, skipping.
2025-10-05 04:40:59.107 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-08-SDP, skipping.
2025-10-05 04:40:59.108 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-07-SDP, skipping.
2025-10-05 04:40:59.108 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-01-SDP, skipping.
2025-10-05 04:40:59.108 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-14-SDP, skipping.
2025-10-05 04:40:59.115 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-12-SDP, skipping.
2025-10-05 04:40:59.115 | WARNING  | __main__:compare_dataframes:136 - No ground truth for MOT17-03-SDP, skipping.
2025-10-05 04:40:59.115 | INFO     | __main__:main:267 - Running metrics
2025-10-05 04:40:59.124 | INFO     | __main__:main:289 - Completed
2025-10-05 04:42:43.025 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:42:43.661 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:42:43.661 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:42:43.850 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.19s)
2025-10-05 04:42:43.850 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:42:43.864 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:42:44.306 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:42:44.803 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:42:44.803 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:42:45.468 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (123616), thread 'MainThread' (140021006119360):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x7f57fe7e45e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7f57bb0ccc10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 233, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x7f57c8949ab0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7f57980b4250>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 145, in evaluate
    for cur_iter, (imgs, _, info_imgs, ids) in enumerate(
                                       └ []

  File "/home/danny/.local/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               └ <torch.utils.data.dataloader.DataLoader object at 0x7f57980b41c0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 734, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7f5826545f30>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f57b8fda0b0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1516, in _next_data
    return self._process_data(data, worker_id)
           │    │             │     └ 0
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7f57b8fdb250>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7f5826546050>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7f57b8fda0b0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1551, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7f592ccb37f0>
    └ <torch._utils.ExceptionWrapper object at 0x7f57b8fdb250>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/_utils.py", line 769, in reraise
    raise exception
          └ AssertionError('Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/...

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/mot/FastTracker/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 128, in __getitem__
    img, target, img_info, img_id = self.pull_item(index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 102, in pull_item
    assert img is not None
AssertionError

2025-10-05 04:42:48.348 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:42:48.989 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:42:48.989 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:42:49.183 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.19s)
2025-10-05 04:42:49.183 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:42:49.197 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:42:49.628 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:42:50.123 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:42:50.123 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:42:50.782 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (123702), thread 'MainThread' (138453103063488):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x7deaf03e05e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7deaacdccc10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 233, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x7deab7d49ab0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7dea881b0280>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 145, in evaluate
    for cur_iter, (imgs, _, info_imgs, ids) in enumerate(
                                       └ []

  File "/home/danny/.local/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               └ <torch.utils.data.dataloader.DataLoader object at 0x7dea881b04c0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 734, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7deb18141f30>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7deaaac0a4a0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1516, in _next_data
    return self._process_data(data, worker_id)
           │    │             │     └ 0
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7deaaac085b0>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7deb18142050>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7deaaac0a4a0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1551, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7dec1e82f7f0>
    └ <torch._utils.ExceptionWrapper object at 0x7deaaac085b0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/_utils.py", line 769, in reraise
    raise exception
          └ AssertionError('Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/...

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/mot/FastTracker/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 128, in __getitem__
    img, target, img_info, img_id = self.pull_item(index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 102, in pull_item
    assert img is not None
AssertionError

2025-10-05 04:42:56.313 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:42:56.941 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:42:56.941 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:42:57.132 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.19s)
2025-10-05 04:42:57.132 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:42:57.146 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:42:57.563 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:42:58.067 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:42:58.067 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:42:58.737 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (123803), thread 'MainThread' (127595270578624):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x740ae6fdc5e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x740aa39c8c10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 233, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x740aae949ab0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x740a7020c310>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 145, in evaluate
    for cur_iter, (imgs, _, info_imgs, ids) in enumerate(
                                       └ []

  File "/home/danny/.local/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               └ <torch.utils.data.dataloader.DataLoader object at 0x740a7020c130>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 734, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x740b0ed41f30>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x740aa0b3c310>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1516, in _next_data
    return self._process_data(data, worker_id)
           │    │             │     └ 0
           │    │             └ <torch._utils.ExceptionWrapper object at 0x740aa0b3f2e0>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x740b0ed42050>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x740aa0b3c310>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1551, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x740c1542f7f0>
    └ <torch._utils.ExceptionWrapper object at 0x740aa0b3f2e0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/_utils.py", line 769, in reraise
    raise exception
          └ AssertionError('Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/...

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/mot/FastTracker/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 128, in __getitem__
    img, target, img_info, img_id = self.pull_item(index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 102, in pull_item
    assert img is not None
AssertionError

2025-10-05 04:43:01.566 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:43:02.213 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:43:02.213 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:43:02.399 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.19s)
2025-10-05 04:43:02.400 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:43:02.413 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:43:02.821 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:43:03.309 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:43:03.309 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:43:03.953 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (123882), thread 'MainThread' (128192828129728):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x7496083dc5e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7495c4dc4c10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 233, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x7495cfd45ab0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7495a01b0250>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 145, in evaluate
    for cur_iter, (imgs, _, info_imgs, ids) in enumerate(
                                       └ []

  File "/home/danny/.local/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               └ <torch.utils.data.dataloader.DataLoader object at 0x7495a01b00d0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 734, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x74962fb41f30>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7495c2c32560>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1516, in _next_data
    return self._process_data(data, worker_id)
           │    │             │     └ 0
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7495c2c33c40>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x74962fb42050>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7495c2c32560>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1551, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x74973675b7f0>
    └ <torch._utils.ExceptionWrapper object at 0x7495c2c33c40>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/_utils.py", line 769, in reraise
    raise exception
          └ AssertionError('Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/...

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/mot/FastTracker/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 128, in __getitem__
    img, target, img_info, img_id = self.pull_item(index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 102, in pull_item
    assert img is not None
AssertionError

2025-10-05 04:44:56.075 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:44:56.694 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:44:56.695 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:44:56.881 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.19s)
2025-10-05 04:44:56.881 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:44:56.895 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:44:57.306 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:44:57.709 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:44:57.709 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:44:58.353 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (124285), thread 'MainThread' (126194704798144):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x72c4cebe05e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x72c48b6bcc10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 233, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x72c493d49ab0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x72c46016c2e0>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 145, in evaluate
    for cur_iter, (imgs, _, info_imgs, ids) in enumerate(
                                       └ []

  File "/home/danny/.local/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               └ <torch.utils.data.dataloader.DataLoader object at 0x72c46016d630>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 734, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x72c4f693df30>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x72c4895ee560>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1516, in _next_data
    return self._process_data(data, worker_id)
           │    │             │     └ 0
           │    │             └ <torch._utils.ExceptionWrapper object at 0x72c4895efac0>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x72c4f693e050>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x72c4895ee560>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1551, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x72c5fd07f7f0>
    └ <torch._utils.ExceptionWrapper object at 0x72c4895efac0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/_utils.py", line 769, in reraise
    raise exception
          └ AssertionError('Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/...

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/mot/FastTracker/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 128, in __getitem__
    img, target, img_info, img_id = self.pull_item(index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 102, in pull_item
    assert img is not None
AssertionError

2025-10-05 04:45:01.182 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:45:01.832 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:45:01.832 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:45:02.016 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.18s)
2025-10-05 04:45:02.017 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:45:02.031 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:45:02.424 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:45:02.911 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:45:02.912 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:45:03.594 | ERROR    | yolox.core.launch:launch:90 - An error has been caught in function 'launch', process 'MainProcess' (124364), thread 'MainThread' (138326261592512):
Traceback (most recent call last):

  File "/home/danny/mot/FastTracker/tools/track.py", line 355, in <module>
    launch(
    └ <function launch at 0x7dcd67de05e0>

> File "/home/danny/mot/FastTracker/yolox/core/launch.py", line 90, in launch
    main_func(*args)
    │          └ (╒══════════════════╤══════════════════════════════════════════════════════════════════════════════════════════════╕
    │            │ keys  ...
    └ <function main at 0x7dcd248b8c10>

  File "/home/danny/mot/FastTracker/tools/track.py", line 233, in main
    *_, summary = evaluator.evaluate(
                  │         └ <function MOTEvaluator.evaluate at 0x7dcd2cf41ab0>
                  └ <yolox.evaluators.mot_evaluator.MOTEvaluator object at 0x7dcd200c8250>

  File "/home/danny/mot/FastTracker/yolox/evaluators/mot_evaluator.py", line 145, in evaluate
    for cur_iter, (imgs, _, info_imgs, ids) in enumerate(
                                       └ []

  File "/home/danny/.local/lib/python3.10/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               └ <torch.utils.data.dataloader.DataLoader object at 0x7dcd200c8340>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 734, in __next__
    data = self._next_data()
           │    └ <function _MultiProcessingDataLoaderIter._next_data at 0x7dcd8fb3df30>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7dcd227d25c0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1516, in _next_data
    return self._process_data(data, worker_id)
           │    │             │     └ 0
           │    │             └ <torch._utils.ExceptionWrapper object at 0x7dcd227d05e0>
           │    └ <function _MultiProcessingDataLoaderIter._process_data at 0x7dcd8fb3e050>
           └ <torch.utils.data.dataloader._MultiProcessingDataLoaderIter object at 0x7dcd227d25c0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1551, in _process_data
    data.reraise()
    │    └ <function ExceptionWrapper.reraise at 0x7dce962837f0>
    └ <torch._utils.ExceptionWrapper object at 0x7dcd227d05e0>
  File "/home/danny/.local/lib/python3.10/site-packages/torch/_utils.py", line 769, in reraise
    raise exception
          └ AssertionError('Caught AssertionError in DataLoader worker process 0.\nOriginal Traceback (most recent call last):\n  File "/...

AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/danny/mot/FastTracker/yolox/data/datasets/datasets_wrapper.py", line 121, in wrapper
    ret_val = getitem_fn(self, index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 128, in __getitem__
    img, target, img_info, img_id = self.pull_item(index)
  File "/home/danny/mot/FastTracker/yolox/data/datasets/mot.py", line 102, in pull_item
    assert img is not None
AssertionError

2025-10-05 04:45:45.573 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:45:46.215 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:45:46.216 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:45:46.408 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.19s)
2025-10-05 04:45:46.408 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:45:46.421 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:45:46.846 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:45:47.343 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:45:47.343 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:45:58.702 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run021/track_results/MOT17-02-SDP.txt
2025-10-05 04:46:17.055 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run021/track_results/MOT17-04-SDP.txt
2025-10-05 04:46:29.934 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run021/track_results/MOT17-05-SDP.txt
2025-10-05 04:46:37.764 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run021/track_results/MOT17-09-SDP.txt
2025-10-05 04:46:47.706 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run021/track_results/MOT17-10-SDP.txt
2025-10-05 04:47:01.539 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run021/track_results/MOT17-11-SDP.txt
2025-10-05 04:47:13.173 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run021/track_results/MOT17-13-SDP.txt
2025-10-05 04:47:13.205 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 04:47:13.967 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 04:47:14.432 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=0.46s)
2025-10-05 04:47:14.432 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 04:47:14.458 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 04:47:15.337 | INFO     | __main__:main:236 - 
Average forward time: 25.22 ms, Average track time: 3.30 ms, Average inference time: 28.52 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.766
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.964
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.870
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.441
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.727
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.826
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.045
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.369
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.793
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.532
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.761
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.850

2025-10-05 04:47:15.338 | INFO     | __main__:main:256 - Found 21 groundtruths and 7 test files.
2025-10-05 04:47:15.338 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 04:47:15.338 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 04:47:15.338 | INFO     | __main__:main:259 - Loading files.
2025-10-05 04:47:17.699 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-02-SDP...
2025-10-05 04:47:17.913 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-13-SDP...
2025-10-05 04:47:18.084 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-04-SDP...
2025-10-05 04:47:18.615 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-10-SDP...
2025-10-05 04:47:18.789 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-05-SDP...
2025-10-05 04:47:18.974 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-11-SDP...
2025-10-05 04:47:19.181 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-09-SDP...
2025-10-05 04:47:19.309 | INFO     | __main__:main:267 - Running metrics
2025-10-05 04:47:20.267 | INFO     | __main__:main:289 - Completed
2025-10-05 04:47:23.081 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 04:47:23.742 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 04:47:23.743 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 04:47:23.937 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.19s)
2025-10-05 04:47:23.937 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 04:47:23.951 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 04:47:24.426 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 04:47:24.925 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 04:47:24.925 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 04:47:36.466 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run022/track_results/MOT17-02-SDP.txt
2025-10-05 04:47:54.724 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run022/track_results/MOT17-04-SDP.txt
2025-10-05 04:48:07.135 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run022/track_results/MOT17-05-SDP.txt
2025-10-05 04:48:15.125 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run022/track_results/MOT17-09-SDP.txt
2025-10-05 04:48:25.430 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run022/track_results/MOT17-10-SDP.txt
2025-10-05 04:48:39.259 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run022/track_results/MOT17-11-SDP.txt
2025-10-05 04:48:50.941 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run022/track_results/MOT17-13-SDP.txt
2025-10-05 04:48:50.975 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 04:48:51.722 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 04:48:52.172 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=0.45s)
2025-10-05 04:48:52.172 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 04:48:52.193 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 04:48:53.018 | INFO     | __main__:main:236 - 
Average forward time: 24.92 ms, Average track time: 3.65 ms, Average inference time: 28.56 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.766
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.964
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.870
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.441
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.727
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.826
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.045
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.369
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.793
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.533
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.761
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.850

2025-10-05 04:48:53.019 | INFO     | __main__:main:256 - Found 21 groundtruths and 7 test files.
2025-10-05 04:48:53.019 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 04:48:53.019 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 04:48:53.019 | INFO     | __main__:main:259 - Loading files.
2025-10-05 04:48:55.261 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-02-SDP...
2025-10-05 04:48:55.458 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-13-SDP...
2025-10-05 04:48:55.620 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-04-SDP...
2025-10-05 04:48:56.116 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-10-SDP...
2025-10-05 04:48:56.285 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-05-SDP...
2025-10-05 04:48:56.468 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-11-SDP...
2025-10-05 04:48:56.771 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-09-SDP...
2025-10-05 04:48:56.891 | INFO     | __main__:main:267 - Running metrics
2025-10-05 04:48:57.778 | INFO     | __main__:main:289 - Completed
2025-10-05 16:03:59.089 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 16:03:59.736 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 16:03:59.736 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 16:03:59.919 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.18s)
2025-10-05 16:03:59.919 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 16:03:59.932 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 16:04:00.329 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 16:04:01.105 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 16:04:01.105 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 16:04:12.178 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run023/track_results/MOT17-02-SDP.txt
2025-10-05 16:04:29.854 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run023/track_results/MOT17-04-SDP.txt
2025-10-05 16:04:42.351 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run023/track_results/MOT17-05-SDP.txt
2025-10-05 16:04:50.040 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run023/track_results/MOT17-09-SDP.txt
2025-10-05 16:05:00.430 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run023/track_results/MOT17-10-SDP.txt
2025-10-05 16:05:14.303 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run023/track_results/MOT17-11-SDP.txt
2025-10-05 16:05:25.785 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run023/track_results/MOT17-13-SDP.txt
2025-10-05 16:05:25.812 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 16:05:26.548 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 16:05:26.994 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=0.45s)
2025-10-05 16:05:26.994 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 16:05:27.018 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 16:05:27.867 | INFO     | __main__:main:236 - 
Average forward time: 25.10 ms, Average track time: 3.12 ms, Average inference time: 28.21 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.766
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.964
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.870
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.441
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.727
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.826
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.045
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.369
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.793
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.532
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.761
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.850

2025-10-05 16:05:27.868 | INFO     | __main__:main:256 - Found 21 groundtruths and 7 test files.
2025-10-05 16:05:27.868 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 16:05:27.868 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 16:05:27.868 | INFO     | __main__:main:259 - Loading files.
2025-10-05 16:05:30.205 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-02-SDP...
2025-10-05 16:05:30.401 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-13-SDP...
2025-10-05 16:05:30.564 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-04-SDP...
2025-10-05 16:05:31.070 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-10-SDP...
2025-10-05 16:05:31.244 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-05-SDP...
2025-10-05 16:05:31.430 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-11-SDP...
2025-10-05 16:05:31.637 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-09-SDP...
2025-10-05 16:05:31.762 | INFO     | __main__:main:267 - Running metrics
2025-10-05 16:05:32.694 | INFO     | __main__:main:289 - Completed
2025-10-05 16:05:35.810 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 16:05:36.433 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 16:05:36.434 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 16:05:36.613 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.18s)
2025-10-05 16:05:36.613 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 16:05:36.626 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 16:05:37.019 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 16:05:37.481 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 16:05:37.482 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 16:05:48.534 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run024/track_results/MOT17-02-SDP.txt
2025-10-05 16:06:06.613 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run024/track_results/MOT17-04-SDP.txt
2025-10-05 16:06:19.056 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run024/track_results/MOT17-05-SDP.txt
2025-10-05 16:06:26.970 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run024/track_results/MOT17-09-SDP.txt
2025-10-05 16:06:37.371 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run024/track_results/MOT17-10-SDP.txt
2025-10-05 16:06:51.268 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run024/track_results/MOT17-11-SDP.txt
2025-10-05 16:07:02.709 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run024/track_results/MOT17-13-SDP.txt
2025-10-05 16:07:02.740 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 16:07:03.482 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 16:07:03.930 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=0.45s)
2025-10-05 16:07:03.930 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 16:07:03.951 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 16:07:04.770 | INFO     | __main__:main:236 - 
Average forward time: 25.21 ms, Average track time: 3.28 ms, Average inference time: 28.49 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.766
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.964
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.870
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.441
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.727
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.826
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.045
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.369
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.793
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.532
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.761
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.850

2025-10-05 16:07:04.771 | INFO     | __main__:main:256 - Found 21 groundtruths and 7 test files.
2025-10-05 16:07:04.771 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 16:07:04.771 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 16:07:04.771 | INFO     | __main__:main:259 - Loading files.
2025-10-05 16:07:06.947 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-02-SDP...
2025-10-05 16:07:07.141 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-13-SDP...
2025-10-05 16:07:07.299 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-04-SDP...
2025-10-05 16:07:07.794 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-10-SDP...
2025-10-05 16:07:07.961 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-05-SDP...
2025-10-05 16:07:08.141 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-11-SDP...
2025-10-05 16:07:08.339 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-09-SDP...
2025-10-05 16:07:08.563 | INFO     | __main__:main:267 - Running metrics
2025-10-05 16:07:09.440 | INFO     | __main__:main:289 - Completed
2025-10-05 18:31:19.284 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/004_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 18:31:19.902 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 18:31:19.903 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 18:31:20.102 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.20s)
2025-10-05 18:31:20.102 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 18:31:20.121 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 18:31:20.491 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 18:31:20.968 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 18:31:20.968 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 18:31:31.962 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run025/track_results/MOT17-02-SDP.txt
2025-10-05 18:31:49.951 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run025/track_results/MOT17-04-SDP.txt
2025-10-05 18:32:02.192 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run025/track_results/MOT17-05-SDP.txt
2025-10-05 18:32:09.997 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run025/track_results/MOT17-09-SDP.txt
2025-10-05 18:32:20.115 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run025/track_results/MOT17-10-SDP.txt
2025-10-05 18:32:33.703 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run025/track_results/MOT17-11-SDP.txt
2025-10-05 18:32:44.885 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run025/track_results/MOT17-13-SDP.txt
2025-10-05 18:32:44.912 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 18:32:45.650 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 18:32:46.089 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=0.44s)
2025-10-05 18:32:46.090 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 18:32:46.111 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 18:32:46.935 | INFO     | __main__:main:236 - 
Average forward time: 24.81 ms, Average track time: 3.17 ms, Average inference time: 27.98 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.766
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.964
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.870
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.441
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.727
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.826
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.045
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.369
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.793
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.532
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.761
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.850

2025-10-05 18:32:46.936 | INFO     | __main__:main:256 - Found 21 groundtruths and 7 test files.
2025-10-05 18:32:46.936 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 18:32:46.936 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 18:32:46.937 | INFO     | __main__:main:259 - Loading files.
2025-10-05 18:32:49.226 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-02-SDP...
2025-10-05 18:32:49.416 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-13-SDP...
2025-10-05 18:32:49.578 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-04-SDP...
2025-10-05 18:32:50.069 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-10-SDP...
2025-10-05 18:32:50.236 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-05-SDP...
2025-10-05 18:32:50.413 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-11-SDP...
2025-10-05 18:32:50.614 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-09-SDP...
2025-10-05 18:32:50.734 | INFO     | __main__:main:267 - Running metrics
2025-10-05 18:32:51.612 | INFO     | __main__:main:289 - Completed
2025-10-05 18:32:54.410 | INFO     | __main__:main:171 - Args: Namespace(experiment_name='yolox_x_mix_det', name=None, dist_backend='nccl', dist_url=None, batch_size=1, devices=1, local_rank=0, num_machines=1, machine_rank=0, exp_file='exps/example/mot/yolox_x_mix_det.py', fp16=True, fuse=True, trt=False, test=False, speed=False, opts=[], ckpt='pretrained/bytetrack_x_mot17.pth.tar', conf=0.01, nms=0.7, tsize=None, seed=None, track_thresh=0.6, track_buffer=30, match_thresh=0.9, min_box_area=100, config='./configs/005_default.json', mot20=False, data_path='../datasets/MOT17', occ=True)
2025-10-05 18:32:55.035 | INFO     | __main__:main:181 - Model Summary: Params: 99.00M, Gflops: 987.11
2025-10-05 18:32:55.036 | INFO     | yolox.data.datasets.mot:__init__:39 - loading annotations into memory...
2025-10-05 18:32:55.219 | INFO     | yolox.data.datasets.mot:__init__:39 - Done (t=0.18s)
2025-10-05 18:32:55.219 | INFO     | pycocotools.coco:__init__:86 - creating index...
2025-10-05 18:32:55.233 | INFO     | pycocotools.coco:__init__:86 - index created!
2025-10-05 18:32:55.640 | INFO     | __main__:main:204 - loading checkpoint
2025-10-05 18:32:56.070 | INFO     | __main__:main:209 - loaded checkpoint done.
2025-10-05 18:32:56.070 | INFO     | __main__:main:215 - 	Fusing model...
2025-10-05 18:33:07.797 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run026/track_results/MOT17-02-SDP.txt
2025-10-05 18:33:25.903 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run026/track_results/MOT17-04-SDP.txt
2025-10-05 18:33:38.178 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run026/track_results/MOT17-05-SDP.txt
2025-10-05 18:33:46.381 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run026/track_results/MOT17-09-SDP.txt
2025-10-05 18:33:56.768 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run026/track_results/MOT17-10-SDP.txt
2025-10-05 18:34:10.903 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run026/track_results/MOT17-11-SDP.txt
2025-10-05 18:34:22.592 | INFO     | yolox.evaluators.mot_evaluator:write_results:52 - save results to ./YOLOX_outputs/yolox_x_mix_det/run026/track_results/MOT17-13-SDP.txt
2025-10-05 18:34:22.620 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:400 - Evaluate in main process...
2025-10-05 18:34:23.394 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - Loading and preparing results...
2025-10-05 18:34:23.841 | INFO     | yolox.evaluators.mot_evaluator:evaluate_prediction:429 - DONE (t=0.45s)
2025-10-05 18:34:23.842 | INFO     | pycocotools.coco:loadRes:367 - creating index...
2025-10-05 18:34:23.865 | INFO     | pycocotools.coco:loadRes:367 - index created!
2025-10-05 18:34:24.709 | INFO     | __main__:main:236 - 
Average forward time: 25.42 ms, Average track time: 3.49 ms, Average inference time: 28.91 ms
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.766
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.964
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.870
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.441
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.727
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.826
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.045
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.369
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.793
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.533
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.761
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.850

2025-10-05 18:34:24.713 | INFO     | __main__:main:256 - Found 21 groundtruths and 7 test files.
2025-10-05 18:34:24.713 | INFO     | __main__:main:257 - Available LAP solvers ['lap', 'scipy']
2025-10-05 18:34:24.713 | INFO     | __main__:main:258 - Default LAP solver 'lap'
2025-10-05 18:34:24.713 | INFO     | __main__:main:259 - Loading files.
2025-10-05 18:34:26.972 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-02-SDP...
2025-10-05 18:34:27.171 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-13-SDP...
2025-10-05 18:34:27.337 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-04-SDP...
2025-10-05 18:34:27.843 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-10-SDP...
2025-10-05 18:34:28.016 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-05-SDP...
2025-10-05 18:34:28.202 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-11-SDP...
2025-10-05 18:34:28.410 | INFO     | __main__:compare_dataframes:132 - Comparing MOT17-09-SDP...
2025-10-05 18:34:28.533 | INFO     | __main__:main:267 - Running metrics
2025-10-05 18:34:29.445 | INFO     | __main__:main:289 - Completed
